name: play_pointz
description: play_pointz APP.


publish_to: 'none' 


version: 2.0.1+375


environment:
  sdk: ">=2.7.1\ <3.0.0"


dependencies:
  flutter:
    sdk: flutter
    
  font_awesome_flutter: ^9.2.0

  bootstrap_icons: ^1.7.2

  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  path_provider: ^2.0.9
  cookie_jar: ^3.0.1
  app_links: ^3.0.1
  shared_preferences: ^2.0.13
  image_picker: ^0.8.5

 

  cached_network_image: ^3.2.0 
  share_plus: ^4.0.4
  clipboard: ^0.1.3
  carousel_slider: ^4.1.1
  get: ^4.6.5

  timeago: ^3.2.2

  intl: ^0.17.0

  flutter_screenutil: ^5.5.3+2
  shimmer: ^2.0.0

  lottie: ^1.3.0
  convex_bottom_bar: ^3.0.0
  google_fonts: ^3.0.1
  pin_code_fields: ^7.4.0
  supercharged: ^2.1.1
  simple_animations: ^4.0.0
  dots_indicator: ^2.1.0
  image_cropper: ^2.0.3

  countup: ^0.1.4
  url_launcher: ^6.1.5
  rflutter_alert: ^2.0.4
  flutter_linkify: ^5.0.2
  video_player: ^2.4.5
  flick_video_player: ^0.5.0
  visibility_detector: ^0.3.3
  expandable_text: ^2.3.0
  keyboard_dismisser: ^3.0.0
  cupertino_back_gesture: ^0.1.0
  dot_navigation_bar: ^1.0.0
  confetti: ^0.7.0
  firebase_messaging: ^14.1.2

  cloud_firestore: ^4.1.0  
  audioplayers: ^1.0.1
  flutter_spinkit: ^5.1.0
  flutter_vibrate: ^1.3.0

  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.2

  firebase_dynamic_links: ^5.0.8
  social_share: ^2.3.1
  flutter_html: ^3.0.0-alpha.6
  restart_app: ^1.1.0+1
  new_version: ^0.3.1
  new_version_plus: ^0.0.3
  store_redirect: ^2.0.1
  pinput: ^2.2.21
  flutter_easyloading: ^3.0.5


  flutter_windowmanager: ^0.0.1+1
  app_tracking_transparency: ^2.0.3
  facebook_app_events: ^0.12.0
  platform_device_id: ^1.0.1
  youtube_player_flutter: ^8.1.2
  screen_protector: ^1.2.0 
  permission_handler: ^10.2.0
  image_downloader: ^0.31.0
  socket_io_client: ^2.0.2
  flutter_pdfview: ^1.3.1
  downloads_path_provider_28: ^0.1.2
  google_mobile_ads: ^1.1.0
  provider: ^6.0.2
  webview_flutter: ^4.2.2
  logger: ^2.0.2+1
  percent_indicator:
  chat_bubbles: ^1.4.0
  giphy_picker: ^2.0.0
  flutter_svg: any
  any_link_preview: ^3.0.0
  animate_do: ^3.0.2
 
  draggable_bottom_sheet: ^1.0.2
  animated_dashed_circle: ^0.0.4
  smooth_page_indicator: ^1.1.0
  story_view: ^0.16.0


 



  
 





  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.4

  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/launcher_icon.png"
  min_sdk_android: 21 
  


flutter:


  uses-material-design: true


  assets:
    - assets/logos/
    - assets/bg/
    - assets/dp/
    - assets/lottie/
    - assets/new/
    - assets/bottom_navbar/
    - assets/popups/
    - assets/popups/game_popups/game1/
    - assets/popups/game_popups/space-hero/
    - assets/popups/game_popups/speed-over-water/
    - assets/popups/game_popups/cat_3_match/
    - assets/audio/
    - assets/connect_assets/
    - assets/new_play_section/
   
    #- assets/rsa_key/private.pem
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100

    - family: RobotMono
      fonts:
        - asset: assets/fonts/RobotoMono-Italic-VariableFont_wght.ttf

    - family: Arial
      fonts:
        - asset: assets/fonts/ARIAL.TTF
    - family: pixelart
      fonts:
        - asset: assets/fonts/pixelart.ttf



   

  